# Generated by Django 3.0.6 on 2020-05-22 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='choice',
            field=models.CharField(choices=[('m', 'male'), ('f', 'female')], default='m', max_length=10),
            preserve_default=False,
        ),
    ]
