# Generated by Django 3.0.6 on 2020-05-22 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_product_choice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='choice',
        ),
        migrations.AlterField(
            model_name='product',
            name='gender',
            field=models.CharField(choices=[('m', 'Male'), ('f', 'Female')], default='m', max_length=1),
            preserve_default=False,
        ),
    ]
