# Generated by Django 3.0.6 on 2020-05-23 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20200523_0136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('k', 'Koton'), ('lc', 'LC Waikiki'), ('hm', 'H&M')], max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('bk', 'Black'), ('wh', 'White'), ('bl', 'Blue'), ('rd', 'Red'), ('yl', 'Yellow'), ('gr', 'Green')], default='bk', max_length=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='season',
            field=models.CharField(choices=[('s', 'Summer'), ('w', 'Winter')], default='w', max_length=4),
            preserve_default=False,
        ),
    ]
