# Generated by Django 3.0.6 on 2020-05-23 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_auto_20200523_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.CharField(choices=[('k', 'Koton'), ('lc', 'LC Waikiki'), ('hm', 'H&M')], default='lc', max_length=2),
            preserve_default=False,
        ),
    ]
