# Generated by Django 3.0.6 on 2020-05-23 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_auto_20200523_0223'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(choices=[('3m', '0-3 M'), ('6m', '3-6 M'), ('9m', '6-9 M'), ('12m', '12 M'), ('18m', '18 M'), ('24m', '24 M'), ('3y', '2-3 Y'), ('4y', '3-4 Y'), ('5y', '4-5 Y'), ('6y', '5-6 Y'), ('7y', '6-7 Y'), ('8y', '7-8 Y'), ('9y', '8-9 Y'), ('10y', '9-10 Y'), ('11y', '10-11 Y'), ('12y', '11-12 Y')], default='3m', max_length=3),
            preserve_default=False,
        ),
    ]
