# Generated by Django 3.0.6 on 2020-05-24 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20200523_0256'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('sh', 'shoes'), ('ac', 'accessories'), ('cl', 'clothes')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(choices=[('bk', 'Black'), ('wh', 'White'), ('bl', 'Blue'), ('rd', 'Red'), ('yl', 'Yellow'), ('gr', 'Green'), ('cf', 'colorful')], max_length=2),
        ),
        migrations.AlterField(
            model_name='product',
            name='season',
            field=models.CharField(choices=[('s', 'Summer'), ('w', 'Winter'), ('a', 'all')], max_length=4),
        ),
        migrations.AlterField(
            model_name='product',
            name='size',
            field=models.CharField(blank=True, choices=[('3m', '0-3 M'), ('6m', '3-6 M'), ('9m', '6-9 M'), ('12m', '12 M'), ('18m', '18 M'), ('24m', '24 M'), ('3y', '2-3 Y'), ('4y', '3-4 Y'), ('5y', '4-5 Y'), ('6y', '5-6 Y'), ('7y', '6-7 Y'), ('8y', '7-8 Y'), ('9y', '8-9 Y'), ('10y', '9-10 Y'), ('11y', '10-11 Y'), ('12y', '11-12 Y'), ('13y', '12-13 Y'), ('13y', '13-14 Y'), ('nul', 'No Size')], max_length=3),
        ),
    ]
